---
# Source: phpmyadmin/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-phpmyadmin
data:
  config.user.inc.php: |-
    <?php
    declare(strict_types=1);
    $cfg['blowfish_secret'] = 'mLtg&D&Kbi%fFix$B6kFcxmVw!igVj48';
    $i = 0;
    $i++;
    $cfg['Servers'][$i]['auth_type'] = 'cookie';
    $cfg['Servers'][$i]['host'] = 'mysql-service';
    $cfg['Servers'][$i]['compress'] = false;
    $cfg['Servers'][$i]['AllowNoPassword'] = false;
    // $cfg['Servers'][$i]['controlhost'] = '';
    // $cfg['Servers'][$i]['controlport'] = '';
    // $cfg['Servers'][$i]['controluser'] = 'pma';
    // $cfg['Servers'][$i]['controlpass'] = 'pmapass';
    // $cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
    // $cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
    // $cfg['Servers'][$i]['relation'] = 'pma__relation';
    // $cfg['Servers'][$i]['table_info'] = 'pma__table_info';
    // $cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
    // $cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
    // $cfg['Servers'][$i]['column_info'] = 'pma__column_info';
    // $cfg['Servers'][$i]['history'] = 'pma__history';
    // $cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
    // $cfg['Servers'][$i]['tracking'] = 'pma__tracking';
    // $cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
    // $cfg['Servers'][$i]['recent'] = 'pma__recent';
    // $cfg['Servers'][$i]['favorite'] = 'pma__favorite';
    // $cfg['Servers'][$i]['users'] = 'pma__users';
    // $cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
    // $cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
    // $cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
    // $cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
    // $cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
    // $cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';
    $cfg['UploadDir'] = '';
    $cfg['SaveDir'] = '';
    //$cfg['RowActionType'] = 'icons';
    //$cfg['ShowAll'] = true;
    //$cfg['MaxRows'] = 50;
    //$cfg['ProtectBinary'] = false;
    //$cfg['DefaultLang'] = 'en';
    //$cfg['DefaultLang'] = 'de';
    //$cfg['PropertiesNumColumns'] = 2;
    //$cfg['QueryHistoryDB'] = true;
    //$cfg['QueryHistoryMax'] = 100;
    //$cfg['SendErrorReports'] = 'always';
    //$cfg['URLQueryEncryption'] = true;
    //$cfg['URLQueryEncryptionSecretKey'] = '';
---
# Source: phpmyadmin/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-phpmyadmin
  labels:
    helm.sh/chart: phpmyadmin-0.1.0
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/version: "5.2.1-apache"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/instance: mysql
---
# Source: phpmyadmin/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-phpmyadmin
  labels:
    helm.sh/chart: phpmyadmin-0.1.0
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/version: "5.2.1-apache"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: phpmyadmin
      app.kubernetes.io/instance: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: phpmyadmin
        app.kubernetes.io/instance: mysql
    spec:
      serviceAccountName: default
      securityContext: {}
      containers:
        - name: phpmyadmin
          securityContext: {}
          image: "docker.io/library/phpmyadmin:5.2.1-apache"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: UPLOAD_LIMIT
              value: 102400K
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 128Mi
          volumeMounts:
            - name: config1
              mountPath: /etc/phpmyadmin/config.user.inc.php
              subPath: config.user.inc.php
      volumes:
        - name: config1
          configMap:
            name: config-phpmyadmin
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: mysql
                topologyKey: topology.kubernetes.io/zone
              weight: 100
