apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    run: php8-nginx
  name: php8-configmap-nginx
data:
  nginx.conf: |
    server {
      listen 80;
      listen [::]:80;
      access_log off;
      root /var/www/html/;
      index index.php index.html index.htm;
      server_name _;
      server_tokens on;
      location / {
          try_files $uri $uri/ /index.php?$args;
      }
      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php8-phpfpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
      }
    }
